### ISSUE TITLE
Elasticsearch Docker failure - data filling up docker image

### ISSUE THREAD

**Issue by phantomanalytical** [codechimp-org/unraid-docker-templates#1]
FIrst off, thanks for these templates. At first, I had no problems running the ELK stack dockers on my unraid for a month or two, but then I started to get warnings about a docker image filling to capacity. I used cadvisor to see which docker was causing the issue and found that the Elasticsearch docker was over 11 GB. At this point, the docker was shutting down on its own shortly after startup, and when I did have it up and running my Kibana searches would time out, even if only searching 15 minutes back. 

I think the issue is likely that I need to save my data off elsewhere but it's currently just filling up the docker container. Do you know how I can send my data elsewhere (and maybe even age it off after x amount of time)? I vim'd all of the config files I could find when ssh'd into the docker, but didn't see anything regarding where to store data.

Any help is much appreciated! Thanks again for the templates.

P.S. the "data" in question is just bro logs being sent over syslog to Logstash from a sensor on my network

**Comment by andrew-codechimp** [comment]
This was an experimental docker image/template which I don't use anymore so I'm afraid I don't have a solution for this.  Just putting it out there to allow anyone to use as a starting point.
I don't have time/inclination to look at this again unfortunately so happy for you take/adapt to get it more functional.
